name: Build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/third-party-actions@actions/setup-node
        with:
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm install

      - name: Run Linter and Tests
        run: npm test

      - name: Bundle Host
        run: npm run bundle-host

      - name: Assume role
        uses: Brightspace/third-party-actions@aws-actions/configure-aws-credentials
        if: startsWith(github.ref, 'refs/tags/')
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          role-to-assume: "arn:aws:iam::771734770799:role/r+Brightspace+frau-jwt+repo"
          role-duration-seconds: 3600
          aws-region: us-east-1

      - name: Publish to CDN
        if: startsWith(github.ref, 'refs/tags/')
        run: npm run publish:cdn

      - name: Publish to NPM
        if: startsWith(github.ref, 'refs/tags/')
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
