name: CI
on: pull_request
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Get Git Info
        run: |
          [[ "${GITHUB_REF}" =~ ^refs/tags/ ]] && GIT_TAG=${GITHUB_REF/refs\/tags\//}
          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
          echo "GIT_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
      - name: Setup Node
        uses: Brightspace/third-party-actions@actions/setup-node
        with:
          node-version: 16.x
      - name: Install Dependencies
        run: npm i
      - name: Test
        run: npm test
      - name: Bundle
        run: npm run bundle-host